# Generated by Django 5.2.4 on 2025-07-24 08:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gorev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Görev Başlığı')),
                ('aciklama', models.TextField(verbose_name='Görev Açıklaması')),
                ('durum', models.CharField(choices=[('BSL', 'Başlatılmadı'), ('DVM', 'Devam Ediyor'), ('TMM', 'Tamamlandı'), ('IPT', 'İptal Edildi')], default='BSL', max_length=3, verbose_name='Görev Durumu')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('baslama_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Başlama Tarihi')),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='gorev_dosyalari/', verbose_name='Ek Dosya')),
                ('puan', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Görev Puanı')),
                ('atan_yetkili', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atanan_gorevler', to=settings.AUTH_USER_MODEL, verbose_name='Atayan Yetkili')),
                ('atanan_calisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorevlerim', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Çalışan')),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Göervler',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
