# Generated by Django 5.2.4 on 2025-07-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorevler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gorev',
            options={'ordering': ['-olusturma_tarihi'], 'verbose_name': 'Görev', 'verbose_name_plural': 'Görevler'},
        ),
        migrations.AddField(
            model_name='gorev',
            name='son_teslim_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Son Teslim Tarihi'),
        ),
    ]
